server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: hz-dream
  datasource:
    url: jdbc:h2:mem:dream;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hz.dream.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hz.dream: debug